### ISSUE TITLE
сконфигурировать keycloak 

### ISSUE THREAD

**Issue by avmlds** [hc-solutions/medical_app#10]
Включить проверку aud при попытке декодировать JWT
https://stackoverflow.com/questions/53550321/keycloak-gatekeeper-aud-claim-and-client-id-do-not-match

**Comment by apolivin** [comment]
Надо задеплоить Keycloak в кубер
https://www.keycloak.org/getting-started/getting-started-kube#_before_you_start

**Comment by avmlds** [comment]
> Надо задеплоить Keycloak в кубер https://www.keycloak.org/getting-started/getting-started-kube#_before_you_start

Так нам он все-таки нужен или нет?
